apiVersion: v1
kind: Pod
metadata:
  name: busybox-DallinStimpson
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox-DallinStimpson
  restartPolicy: Always